services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: projectx-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: dev-file
    ports:
      - "9090:8080"
    command: start-dev

volumes:
  keycloak_data: 